image: node:24

stages:
  - build
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

build-job:
  stage: build
  script:
    - npm ci
    - npm run build
  artifacts:
    expire_in: 14 days
    paths:
      - dist/win/digitaltwincity-interface/

deploy-manually:
  stage: deploy
  when: manual
  tags:
    - windows
  script:
    - powershell Compress-Archive -Path dist/win/digitaltwincity-interface -DestinationPath DigitalTwinCityInterface.zip -Force
  artifacts:
    expire_in: 14 days
    paths:
      - DigitalTwinCityInterface.zip
