export enum FoodType {
	nötkött = "nötkött",
	lammkött = "lammkött",
	fläskkött = "fläskkött",
	fågelkött = "fågelkött",
	korv_chark = "korv_chark",
	annan_inälvsmat = "annan_inälvsmat",
	fisk_skaldjur = "fisk_skaldjur",
	ägg = "ägg",
	mjölk_fil_yoghurt = "mjölk_fil_yoghurt",
	grädde = "grädde",
	ost = "ost",
	smör = "smör",
	ris = "ris",
	potatis = "potatis",
	pasta = "pasta",
	bröd = "bröd",
	mjöl_gryn_socker = "mjöl_gryn_socker",
	frukt_sverige = "frukt_sverige",
	frukt_import = "frukt_import",
	bär = "bär",
	nötter = "nötter",
	salladsgrönsaker = "salladsgrönsaker",
	rotfrukter_lök_kål = "rotfrukter_lök_kål",
	margarin = "margarin",
	matolja = "matolja",
	såser_kryddor = "såser_kryddor",
	godis_choklad = "godis_choklad",
	chips = "chips",
	glass = "glass",
	kakor_bullar = "kakor_bullar",
	kaffe_te = "kaffe_te",
	saft_juice_läsk = "saft_juice_läsk",
	öl = "öl",
	vin_sprit = "vin_sprit",
}

export enum FoodCategory {
	animaliskt = "Animaliska proteinkällor",
	mejeriprodukter = "Mejeriprodukter",
	kolhydratkällor = "Kolhydratkällor",
	frukt_och_grönt = "Frukt och grönt",
	fetter_såser_och_kryddor = "Fetter, såser och kryddor",
	sötsaker_och_chips = "Sötsaker och chips",
	drycker_och_alkohol = "Drycker och alkohol",
}

export interface FoodData {
	image: string;
	category: FoodCategory;
	co2: number;
	land: number;
	nitrogen: number;
	phosphorus: number;
	water: number;
	biodiversity: number;
	pesticides: number;
	note: string;
}

type FoodItems = {
	[key in FoodType]: FoodData;
};

export const foodItems: FoodItems = {
	// Animaliska proteinkällor
	[FoodType.nötkött]: {
		image: "protein-beef+icon",
		category: FoodCategory.animaliskt,
		co2: 29.0,
		land: 119.0,
		nitrogen: 1090.0,
		phosphorus: 27.0,
		water: 210.0,
		biodiversity: 1.9,
		pesticides: 1.5,
		note: "Per kilo benfritt kött",
	},
	[FoodType.lammkött]: {
		image: "protein-lamb+icon",
		category: FoodCategory.animaliskt,
		co2: 29.0,
		land: 212.0,
		nitrogen: 750.0,
		phosphorus: 61.0,
		water: 470.0,
		biodiversity: 110.0,
		pesticides: 0.9,
		note: "Per kilo benfritt kött",
	},
	[FoodType.fläskkött]: {
		image: "protein-pork+icon",
		category: FoodCategory.animaliskt,
		co2: 7.0,
		land: 13.0,
		nitrogen: 160.0,
		phosphorus: 16.0,
		water: 340.0,
		biodiversity: 0.31,
		pesticides: 0.6,
		note: "Per kilo benfritt kött",
	},
	[FoodType.fågelkött]: {
		image: "protein-chicken+icon",
		category: FoodCategory.animaliskt,
		co2: 3.8,
		land: 8.7,
		nitrogen: 120.0,
		phosphorus: 14.0,
		water: 15.0,
		biodiversity: 0.57,
		pesticides: 0.6,
		note: "Per kilo benfritt kött",
	},
	[FoodType.korv_chark]: {
		image: "protein-brawn",
		category: FoodCategory.animaliskt,
		co2: 7.2,
		land: 26.0,
		nitrogen: 250.0,
		phosphorus: 9.0,
		water: 110.0,
		biodiversity: 0.44,
		pesticides: 0.4,
		note: "Per kilo falukorv (40 % kötthalt, 50-50 nöt-gris)",
	},
	[FoodType.annan_inälvsmat]: {
		image: "protein-beefMince",
		category: FoodCategory.animaliskt,
		co2: 0.7,
		land: 2.1,
		nitrogen: 22.0,
		phosphorus: 1.0,
		water: 15.0,
		biodiversity: 0.04,
		pesticides: 0.05,
		note: "Per kilo",
	},
	[FoodType.fisk_skaldjur]: {
		image: "protein-salmon",
		category: FoodCategory.animaliskt,
		co2: 5.8,
		land: 1.4,
		nitrogen: 22.0,
		phosphorus: 3.0,
		water: 15.0,
		biodiversity: 0.18,
		pesticides: 0.2,
		note: "Per kilo ätbart",
	},
	[FoodType.ägg]: {
		image: "protein-egg",
		category: FoodCategory.animaliskt,
		co2: 2.3,
		land: 4.7,
		nitrogen: 63.0,
		phosphorus: 7.0,
		water: 9.0,
		biodiversity: 0.24,
		pesticides: 0.4,
		note: "Per kilo med skal",
	},

	// Mejeriprodukter
	[FoodType.mjölk_fil_yoghurt]: {
		image: "dairy-milk",
		category: FoodCategory.mejeriprodukter,
		co2: 1.2,
		land: 4.4,
		nitrogen: 49.0,
		phosphorus: 2.0,
		water: 10.0,
		biodiversity: 0.06,
		pesticides: 0.1,
		note: "Per liter",
	},
	[FoodType.grädde]: {
		image: "dairy-yogurt",
		category: FoodCategory.mejeriprodukter,
		co2: 5.7,
		land: 23.0,
		nitrogen: 260.0,
		phosphorus: 8.0,
		water: 40.0,
		biodiversity: 0.33,
		pesticides: 0.5,
		note: "Per liter",
	},
	[FoodType.ost]: {
		image: "dairy-cheese1",
		category: FoodCategory.mejeriprodukter,
		co2: 9.2,
		land: 35.0,
		nitrogen: 390.0,
		phosphorus: 13.0,
		water: 50.0,
		biodiversity: 0.5,
		pesticides: 0.8,
		note: "Per kilo",
	},
	[FoodType.smör]: {
		image: "other butter_",
		category: FoodCategory.mejeriprodukter,
		co2: 11.0,
		land: 45.0,
		nitrogen: 490.0,
		phosphorus: 16.0,
		water: 70.0,
		biodiversity: 0.63,
		pesticides: 1.1,
		note: "Per kilo",
	},

	// Kolhydratkällor

	[FoodType.ris]: {
		image: "grain-rice-2",
		category: FoodCategory.kolhydratkällor,
		co2: 3.5,
		land: 4.5,
		nitrogen: 56.0,
		phosphorus: 13.0,
		water: 710.0,
		biodiversity: 3.2,
		pesticides: 0.9,
		note: "Per kilo torrvara",
	},
	[FoodType.potatis]: {
		image: "vege-potato1",
		category: FoodCategory.kolhydratkällor,
		co2: 0.4,
		land: 0.5,
		nitrogen: 5.0,
		phosphorus: 3.0,
		water: 10.0,
		biodiversity: 0.01,
		pesticides: 0.2,
		note: "Per kilo med skal",
	},
	[FoodType.pasta]: {
		image: "grain-pasta",
		category: FoodCategory.kolhydratkällor,
		co2: 1.6,
		land: 3.0,
		nitrogen: 40.0,
		phosphorus: 3.0,
		water: 0.0,
		biodiversity: 0.0,
		pesticides: 0.2,
		note: "Per kilo torrvara",
	},
	[FoodType.bröd]: {
		image: "grain-bread1",
		category: FoodCategory.kolhydratkällor,
		co2: 1.0,
		land: 1.7,
		nitrogen: 18.0,
		phosphorus: 2.0,
		water: 0.0,
		biodiversity: 0.01,
		pesticides: 0.2,
		note: "Per kilo",
	},
	[FoodType.mjöl_gryn_socker]: {
		image: "grain-oats",
		category: FoodCategory.kolhydratkällor,
		co2: 1.1,
		land: 2.1,
		nitrogen: 24.0,
		phosphorus: 3.0,
		water: 10.0,
		biodiversity: 0.02,
		pesticides: 0.3,
		note: "Per kilo torrvara",
	},

	// Frukt och grönt
	[FoodType.frukt_sverige]: {
		image: "fruit-apple",
		category: FoodCategory.frukt_och_grönt,
		co2: 0.2,
		land: 0.8,
		nitrogen: 4.0,
		phosphorus: 1.0,
		water: 0.0,
		biodiversity: 0.01,
		pesticides: 0.3,
		note: "Per kilo med skal",
	},
	[FoodType.frukt_import]: {
		image: "fruit-banana",
		category: FoodCategory.frukt_och_grönt,
		co2: 0.6,
		land: 0.7,
		nitrogen: 6.0,
		phosphorus: 2.0,
		water: 110.0,
		biodiversity: 1.1,
		pesticides: 0.9,
		note: "Per kilo med skal",
	},
	[FoodType.bär]: {
		image: "fruit-berry",
		category: FoodCategory.frukt_och_grönt,
		co2: 0.8,
		land: 1.9,
		nitrogen: 15.0,
		phosphorus: 3.0,
		water: 50.0,
		biodiversity: 0.02,
		pesticides: 1.3,
		note: "Per kilo med skal",
	},
	[FoodType.nötter]: {
		image: "nuts",
		category: FoodCategory.frukt_och_grönt,
		co2: 2.9,
		land: 12.0,
		nitrogen: 120.0,
		phosphorus: 4.0,
		water: 1900.0,
		biodiversity: 8.6,
		pesticides: 5.6,
		note: "Per kilo utan skal",
	},
	[FoodType.salladsgrönsaker]: {
		image: "vege-salad",
		category: FoodCategory.frukt_och_grönt,
		co2: 0.8,
		land: 0.2,
		nitrogen: 4.0,
		phosphorus: 2.0,
		water: 10.0,
		biodiversity: 0.09,
		pesticides: 0.2,
		note: "Per kilo med skal",
	},
	[FoodType.rotfrukter_lök_kål]: {
		image: "vege-onion",
		category: FoodCategory.frukt_och_grönt,
		co2: 0.4,
		land: 0.5,
		nitrogen: 8.0,
		phosphorus: 2.0,
		water: 30.0,
		biodiversity: 0.12,
		pesticides: 0.4,
		note: "Per kilo med skal",
	},

	// Fetter, såser och kryddor
	[FoodType.margarin]: {
		image: "other butter_",
		category: FoodCategory.fetter_såser_och_kryddor,
		co2: 1.7,
		land: 3.0,
		nitrogen: 36.0,
		phosphorus: 5.0,
		water: 0.0,
		biodiversity: 1.6,
		pesticides: 0.4,
		note: "Per kilo",
	},
	[FoodType.matolja]: {
		image: "matolja",
		category: FoodCategory.fetter_såser_och_kryddor,
		co2: 2.6,
		land: 15.0,
		nitrogen: 91.0,
		phosphorus: 30.0,
		water: 760.0,
		biodiversity: 15.0,
		pesticides: 13.0,
		note: "Per liter",
	},
	[FoodType.såser_kryddor]: {
		image: "såser_kryddor",
		category: FoodCategory.fetter_såser_och_kryddor,
		co2: 1.4,
		land: 4.4,
		nitrogen: 44.0,
		phosphorus: 4.0,
		water: 130.0,
		biodiversity: 0.76,
		pesticides: 0.6,
		note: "Per kilo",
	},

	// Sötsaker och chips
	[FoodType.godis_choklad]: {
		image: "snack-chocolate",
		category: FoodCategory.sötsaker_och_chips,
		co2: 4.7,
		land: 21.0,
		nitrogen: 110.0,
		phosphorus: 62.0,
		water: 30.0,
		biodiversity: 9.6,
		pesticides: 11.0,
		note: "Per kilo",
	},
	[FoodType.chips]: {
		image: "snack-chips",
		category: FoodCategory.sötsaker_och_chips,
		co2: 2.7,
		land: 2.6,
		nitrogen: 27.0,
		phosphorus: 13.0,
		water: 50.0,
		biodiversity: 1.8,
		pesticides: 0.9,
		note: "Per kilo",
	},
	[FoodType.glass]: {
		image: "snack-icecream",
		category: FoodCategory.sötsaker_och_chips,
		co2: 2.2,
		land: 7.0,
		nitrogen: 74.0,
		phosphorus: 4.0,
		water: 40.0,
		biodiversity: 0.09,
		pesticides: 0.9,
		note: "Per liter",
	},
	[FoodType.kakor_bullar]: {
		image: "grain-bulle",
		category: FoodCategory.sötsaker_och_chips,
		co2: 1.2,
		land: 2.7,
		nitrogen: 29.0,
		phosphorus: 3.0,
		water: 2.0,
		biodiversity: 0.31,
		pesticides: 0.4,
		note: "Per kilo",
	},

	// Drycker och alkohol
	[FoodType.kaffe_te]: {
		image: "drink-coffee",
		category: FoodCategory.drycker_och_alkohol,
		co2: 6.1,
		land: 29.0,
		nitrogen: 190.0,
		phosphorus: 40.0,
		water: 2310.0,
		biodiversity: 10.0,
		pesticides: 21.0,
		note: "Per liter",
	},
	[FoodType.saft_juice_läsk]: {
		image: "drink-soda",
		category: FoodCategory.drycker_och_alkohol,
		co2: 0.8,
		land: 0.9,
		nitrogen: 9.0,
		phosphorus: 2.0,
		water: 60.0,
		biodiversity: 0.26,
		pesticides: 0.6,
		note: "Per liter",
	},
	[FoodType.öl]: {
		image: "drink-beer",
		category: FoodCategory.drycker_och_alkohol,
		co2: 0.5,
		land: 0.7,
		nitrogen: 6.0,
		phosphorus: 1.0,
		water: 1.0,
		biodiversity: 0.0,
		pesticides: 0.03,
		note: "Per liter",
	},
	[FoodType.vin_sprit]: {
		image: "drink-wine",
		category: FoodCategory.drycker_och_alkohol,
		co2: 2.3,
		land: 4.3,
		nitrogen: 46.0,
		phosphorus: 10.0,
		water: 90.0,
		biodiversity: 1.1,
		pesticides: 1.3,
		note: "Per liter",
	},
};
